# unlike volume which is local to a pod, persistent volume is isn't local to a container and 
#stored on the host machine
#hence data won't be lost even if pod crashed.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: database-persistent-volume-claim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi